import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import EmployeeProfilesTable from "App/models/EmployeeListModel";

export default class EmployeeSeeder extends BaseSeeder {
  public async run () {
    // Write your database queries inside the run method
    await EmployeeProfilesTable.createMany([
      {
        first_name: "Sarah",
        last_name: "Anga",
        birthdate: "1998-07-23",
        gender: "Female",
        marital_status: "Single",
        department: "Admin",
        position: "Account Broker",
        date_hired: "1978-10-10",
        employment_status: "Casual",
        contact_number: 1433406538,
        email: "bbeyne0@stanford.edu",
        address: "073 Luster Circle",
        city: "Morant Bay",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Mae",
        last_name: "Dilston",
        birthdate: "1984-07-12",
        gender: "Female",
        marital_status: "Married",
        department: "Finance",
        position: "Chief Financial Officer",
        date_hired: "2010-01-04",
        employment_status: "Casual",
        contact_number: 3218443039,
        email: "idilston1@irs.gov",
        address: "42 South Plaza",
        city: "Jämsänkoski",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Shari",
        last_name: "Coxhead",
        birthdate: "1972-09-18",
        gender: "Female",
        marital_status: "Single",
        department: "Finance",
        position: "Appraiser",
        date_hired: "2015-07-06",
        employment_status: "Casual",
        contact_number: 5468168671,
        email: "scoxhead2@comcast.net",
        address: "05104 Gina Hill",
        city: "Negotino",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Barbabas",
        last_name: "Danelutti",
        birthdate: "1964-06-14",
        gender: "Female",
        marital_status: "Single",
        department: "Engineering",
        position: "Applications Engineer",
        date_hired: "2013-11-07",
        employment_status: "Regular",
        contact_number: 3363400431,
        email: "bdanelutti3@auda.org.au",
        address: "205 Vernon Park",
        city: "Pamplona/Iruña",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Zoe",
        last_name: "Eilhart",
        birthdate: "1972-04-17",
        gender: "Male",
        marital_status: "Single",
        department: "Admin",
        position: "Secretary",
        date_hired: "2012-08-16",
        employment_status: "Regular",
        contact_number: 1178942822,
        email: "zeilhart4@businessweek.com",
        address: "45 Main Avenue",
        city: "Kara",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "West",
        last_name: "Massot",
        birthdate: "1968-06-07",
        gender: "Female",
        marital_status: "Single",
        department: "Engineering",
        position: "Civil Engineer",
        date_hired: "2010-07-27",
        employment_status: "Casual",
        contact_number: 3146767822,
        email: "wmassot5@paginegialle.it",
        address: "8 Menomonie Place",
        city: "Sarzedo",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Corinne",
        last_name: "Treat",
        birthdate: "1965-10-08",
        gender: "Male",
        marital_status: "Married",
        department: "Engineering",
        position: "Civil Engineer",
        date_hired: "2020-02-10",
        employment_status: "Casual",
        contact_number: 6937026900,
        email: "ctreat6@comsenz.com",
        address: "6 David Alley",
        city: "Druju",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Judith",
        last_name: "Topp",
        birthdate: "1974-09-14",
        gender: "Bigender",
        marital_status: "Married",
        department: "Finance",
        position: "Credit Analyst",
        date_hired: "2020-07-27",
        employment_status: "Probationary",
        contact_number: 6782846391,
        email: "jtopp7@phpbb.com",
        address: "3 Hanson Junction",
        city: "Moshiyi",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Gallagher",
        last_name: "Kitchingman",
        birthdate: "1996-04-15",
        gender: "Genderfluid",
        marital_status: "Married",
        department: "Engineering",
        position: "Design Engineer",
        date_hired: "2014-11-09",
        employment_status: "Casual",
        contact_number: 7453232184,
        email: "gkitchingman8@photobucket.com",
        address: "7917 Crownhardt Terrace",
        city: "Wichit",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Flossie",
        last_name: "Caldroni",
        birthdate: "1995-06-29",
        gender: "Bigender",
        marital_status: "Married",
        department: "Engineering",
        position: "Design Engineer",
        date_hired: "2019-04-11",
        employment_status: "Regular",
        contact_number: 3973495809,
        email: "fcaldroni9@goo.gl",
        address: "98915 Blue Bill Park Alley",
        city: "Pojan",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Auria",
        last_name: "Ciccarelli",
        birthdate: "1975-09-24",
        gender: "Genderqueer",
        marital_status: "Married",
        department: "Finance",
        position: "Account Executive",
        date_hired: "2012-05-31",
        employment_status: "Casual",
        contact_number: 9802944788,
        email: "aciccarellia@whitehouse.gov",
        address: "5 Bunting Trail",
        city: "Sapataria",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Eleanor",
        last_name: "Diamond",
        birthdate: "1967-08-03",
        gender: "Female",
        marital_status: "Single",
        department: "Admin",
        position: "Administrative assistant",
        date_hired: "2017-10-11",
        employment_status: "Probationary",
        contact_number: 4225634990,
        email: "ediamondb@wsj.com",
        address: "72 Meadow Vale Parkway",
        city: "L'Assomption",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Evelyn",
        last_name: "Volk",
        birthdate: "1997-12-07",
        gender: "Agender",
        marital_status: "Married",
        department: "Finance",
        position: "Appraiser",
        date_hired: "2011-08-23",
        employment_status: "Casual",
        contact_number: 1624349406,
        email: "evolkc@wikia.com",
        address: "6799 Upham Way",
        city: "Wukang",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Everett",
        last_name: "Esche",
        birthdate: "2002-03-15",
        gender: "Male",
        marital_status: "Single",
        department: "Engineering",
        position: "Chemical Engineer",
        date_hired: "2010-08-26",
        employment_status: "Casual",
        contact_number: 6256621125,
        email: "eesched@ovh.net",
        address: "8 Clove Parkway",
        city: "Guanting",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Marieann",
        last_name: "Lebrun",
        birthdate: "1984-12-26",
        gender: "Non-binary",
        marital_status: "Single",
        department: "Finance",
        position: "Account Broker",
        date_hired: "2014-02-11",
        employment_status: "Probationary",
        contact_number: 4208272656,
        email: "mlebrune@guardian.co.uk",
        address: "5918 Hooker Alley",
        city: "Shashūbay",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Emelen",
        last_name: "Bartholin",
        birthdate: "2001-04-10",
        gender: "Male",
        marital_status: "Single",
        department: "Admin",
        position: "Administrative coordinator",
        date_hired: "2015-06-14",
        employment_status: "Probationary",
        contact_number: 2516529806,
        email: "ebartholinf@cloudflare.com",
        address: "29436 Maple Court",
        city: "Nagorsk",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Abbye",
        last_name: "Seymark",
        birthdate: "1978-02-22",
        gender: "Genderfluid",
        marital_status: "Married",
        department: "Admin",
        position: "Administrative coordinator",
        date_hired: "2010-07-23",
        employment_status: "Probationary",
        contact_number: 4956070098,
        email: "aseymarkg@whitehouse.gov",
        address: "8 Dorton Place",
        city: "Stenungsund",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "De witt",
        last_name: "Shoulders",
        birthdate: "1970-02-20",
        gender: "Genderqueer",
        marital_status: "Single",
        department: "Admin",
        position: "Administrative coordinator",
        date_hired: "2014-10-22",
        employment_status: "Regular",
        contact_number: 2904559416,
        email: "dshouldersh@usnews.com",
        address: "7887 Dexter Point",
        city: "Taoshan",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Lexis",
        last_name: "Trethowan",
        birthdate: "1984-04-12",
        gender: "Female",
        marital_status: "Single",
        department: "Admin",
        position: "Administrative coordinator",
        date_hired: "2021-06-13",
        employment_status: "Probationary",
        contact_number: 6703513480,
        email: "ltrethowani@cyberchimps.com",
        address: "2 Gerald Road",
        city: "Dassa-Zoumé",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Cece",
        last_name: "Quayle",
        birthdate: "1978-05-12",
        gender: "Agender",
        marital_status: "Single",
        department: "Admin",
        position: "Administrative manager",
        date_hired: "2008-01-03",
        employment_status: "Casual",
        contact_number: 9141957507,
        email: "cquaylej@icio.us",
        address: "5 Melvin Point",
        city: "Hongos",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Margalo",
        last_name: "Wane",
        birthdate: "2001-11-02",
        gender: "Polygender",
        marital_status: "Married",
        department: "Engineering",
        position: "Civil Engineering Technologist",
        date_hired: "2013-03-11",
        employment_status: "Regular",
        contact_number: 5787543282,
        email: "mwanek@odnoklassniki.ru",
        address: "2 Thompson Parkway",
        city: "Markovo",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Gerta",
        last_name: "Maccrae",
        birthdate: "1966-09-30",
        gender: "Genderqueer",
        marital_status: "Married",
        department: "Admin",
        position: "Receptionist",
        date_hired: "2015-06-16",
        employment_status: "Casual",
        contact_number: 1099880845,
        email: "gmaccrael@hao123.com",
        address: "2089 Packers Trail",
        city: "Uubulan",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Sauveur",
        last_name: "Sarsfield",
        birthdate: "1982-09-01",
        gender: "Agender",
        marital_status: "Married",
        department: "Engineering",
        position: "Design Engineer",
        date_hired: "2019-12-23",
        employment_status: "Casual",
        contact_number: 6806390761,
        email: "ssarsfieldm@rakuten.co.jp",
        address: "1 Mccormick Street",
        city: "Lentisqueira",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Loretta",
        last_name: "Polotti",
        birthdate: "1964-03-12",
        gender: "Genderfluid",
        marital_status: "Married",
        department: "Admin",
        position: "Administrative specialist",
        date_hired: "2020-06-23",
        employment_status: "Regular",
        contact_number: 8425915872,
        email: "lpolottin@intel.com",
        address: "8 Parkside Junction",
        city: "Parlilitan",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Hallsy",
        last_name: "O'Currigan",
        birthdate: "1985-01-14",
        gender: "Agender",
        marital_status: "Married",
        department: "Engineering",
        position: "Civil Engineer",
        date_hired: "2017-01-14",
        employment_status: "Regular",
        contact_number: 2777122829,
        email: "hocurrigano@telegraph.co.uk",
        address: "7929 Service Road",
        city: "Duko",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Edy",
        last_name: "Mannin",
        birthdate: "1983-03-28",
        gender: "Polygender",
        marital_status: "Married",
        department: "Engineering",
        position: "Civil Engineer",
        date_hired: "2008-04-20",
        employment_status: "Regular",
        contact_number: 1339366674,
        email: "emanninp@weibo.com",
        address: "87101 Mariners Cove Circle",
        city: "Taekas",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Ardella",
        last_name: "Peake",
        birthdate: "1992-04-11",
        gender: "Polygender",
        marital_status: "Single",
        department: "Admin",
        position: "Administrative manager",
        date_hired: "2016-12-14",
        employment_status: "Probationary",
        contact_number: 1119993331,
        email: "apeakeq@4shared.com",
        address: "20984 Coolidge Junction",
        city: "Mionica",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Alix",
        last_name: "Peachman",
        birthdate: "1963-07-29",
        gender: "Polygender",
        marital_status: "Single",
        department: "Engineering",
        position: "Applications Engineer",
        date_hired: "2017-07-12",
        employment_status: "Probationary",
        contact_number: 2045885320,
        email: "apeachmanr@dyndns.org",
        address: "2334 Farwell Trail",
        city: "Amboasary",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Tessy",
        last_name: "Frossell",
        birthdate: "1974-09-04",
        gender: "Female",
        marital_status: "Married",
        department: "Finance",
        position: "Appraiser",
        date_hired: "2017-12-28",
        employment_status: "Casual",
        contact_number: 4295308633,
        email: "tfrossells@vimeo.com",
        address: "01705 Bunker Hill Crossing",
        city: "Valença",
        province: "Cebu",
        nationality: "Filipino"
      },
      {
        first_name: "Jessalyn",
        last_name: "Antonowicz",
        birthdate: "1976-03-12",
        gender: "Female",
        marital_status: "Single",
        department: "Engineering",
        position: "Applications Engineer",
        date_hired: "2021-03-29",
        employment_status: "Casual",
        contact_number: 8309239046,
        email: "jantonowiczt@cargocollective.com",
        address: "7676 Old Shore Drive",
        city: "Resplendor",
        province: "Cebu",
        nationality: "Filipino"
      }
    ]);
  }
}
